### ISSUE TITLE
VariationalWarpGP is not available in this repo

### ISSUE THREAD

**Issue by yubailibra** [andrewcharlesjones/spatial-alignment#5]
Hi, we are interested to try the alignment with multimodal inputs (expression + histo image), following the instruction in the "experiments/visium/visium_multimodal_alignment.py". However, the core function "VariationalWarpGP" and its dependencies seem not present in the current repo. Is there a plan to add them to the repo? Thanks much!

**Comment by andrewcharlesjones** [comment]
This has now been fixed -- thanks for bringing it to my attention. The correct class name to use is now `VariationalGPSA`, not `VariationalWarpGP`.
